### ISSUE TITLE
Missing file of "pcwrite"

### ISSUE THREAD

**Issue by ph81323** [shurans/sscnet#1]
Hi @shurans , I like this work a lot and it truly help research in 3D domain. But when I cloned this code and tried to run "evluation_script('../results/','nyucad')" as you suggest in README, it crushed because there isn't any function named pcwrite and pointCloud. Can you reload it? Or where can I find it?
Thanks a lot!

**Comment by andyzeng** [comment]
Hi @ph81323, both pcwrite and pointCloud are a part of Matlab's Computer Vision System Toolbox (requires version 2015a or higher). You can find more information about it [here](https://www.mathworks.com/help/vision/3-d-point-cloud-processing.html). For an alternative, you can also save an array of 3D points to a .ply file with [points2ply](http://vision.princeton.edu/code.html#points2ply).

**Comment by ph81323** [comment]
Oh, I see. Thanks a lot! Maybe it's time to upgrade my Matlab.
