### ISSUE TITLE
F0408 14:40:36.246459 20151 blob.cpp:115] Check failed: data_  *** Check failure stack trace: *** Aborted (core dumped)

### ISSUE THREAD

**Issue by yxliwhu** [shurans/sscnet#10]
When I run the demo "demotest_model.py", I meet this problem. Should I change something in the "demo.txt"? And how could I change the location of the single test image.

**Comment by Fromandto** [comment]
This demo works fine on my machine.

If you find it hard to figure out the file path, maybe you should directly try 'test*model' rather than this single frame demo.

**Comment by yxliwhu** [comment]
Sorry, I have try the "test model", but get the same error. "F0408 14:40:36.246459 20151 blob.cpp:115] Check failed: data_ *** Check failure stack trace: *** Aborted (core dumped) ". That means there is not input data. So, I want to figure out two things:
1. where to  define the location of the input data (at "deploy_net_nyu.txt"?)
2. what data used in this program, .bin or .png?
Thanks

**Comment by Fromandto** [comment]
1. yes
2. bin

**Comment by yxliwhu** [comment]
Thanks for the reply. I have another question. Whether I have to use this program in GPU mode? Because I use a CPU mode now.

**Comment by Fromandto** [comment]
I am afraid you have to use gpu mode, as I only find suncg_data_layer.cu but not suncg_data_layer.cpp.

This is the major difference between this caffe and the official one.

**Comment by yxliwhu** [comment]
Thanks again, I would try it in another GPU mode machine.

**Comment by yxliwhu** [comment]
Sorry, I have another question. which type GPU you used for the test? Because I try to use the G2 instance of AWS and get the error 'cudaSuccess (2 vs. 0)  out of memory'. For the test, whether should I have at least 12G GPU memory?

**Comment by shurans** [comment]
Yes, you also need a 12G GPU memory for testing.

**Comment by Fromandto** [comment]
@yxliwhu I made a mistake, both .png and .bin are used.

**Comment by yxliwhu** [comment]
@Fromandto which type GPU you used for the test?

**Comment by Fromandto** [comment]
a 12gb memory card

**Comment by yxliwhu** [comment]
@Fromandto Do you know how to generate .bin file with own depth data?
