### ISSUE TITLE
what is stored in "*_vol_d4.mat" file?

### ISSUE THREAD

**Issue by yxliwhu** [shurans/sscnet#13]

**Comment by shurans** [comment]
Volume information used for evaluation each voxel encoded in one of following categories:
on the surface 0
free space: 1 
occluded: -1
missing Depth : -2
outside FOV: -3 
outSide room: -4 
outside ceiling: -5

**Comment by yxliwhu** [comment]
How could I generate this file for my own dataset

**Comment by jiunyen-ching** [comment]
Hi @shurans, inside `flipVol_ds`, do the decimal values give any information about their categories? E.g. are '0.5187' or '-0.1957' considered as '0' and thus refer to "on the surface"?
