### ISSUE TITLE
Does SUNCG dataset provide the raw RGB images corresponding to those depth images?

### ISSUE THREAD

**Issue by TracelessLe** [shurans/sscnet#14]
As the title of issue says, would you please share some time to solve the problem?

**Comment by shurans** [comment]
For this project, we didn't use color images. 
You can generate your own RGB-D images use the  [SUNCG toolbox.](https://github.com/shurans/sscnet/#generating-training-data-from-suncg).

Here is another [project](http://3dvision.princeton.edu/projects/2016/PBRS/), where you can download many precompute RGB-D image pairs from SUNCG.
