### ISSUE TITLE
generating SUNCG training data

### ISSUE THREAD

**Issue by shubhtuls** [shurans/sscnet#2]
Hi,
Thanks for providing the toolbox for training the models. I was wondering if you could also add code (or provide rough instructions assuming we download the SUNCG toolbox) to generate the training data stored in data/depthbin/SUNCGtrain*.

**Comment by shurans** [comment]
Absolutely, I 've added the code and script for generating the camera pose, depth map and volumetric ground truth from SUNCG. 
You can follow the instructions in the README: "Generating training data from SUNCG" to generate the data.
Let me know if you have any other questions!

**Comment by shubhtuls** [comment]
Great, thanks for adding this!
