### ISSUE TITLE
Not able to install it properly

### ISSUE THREAD

**Issue by Pratapabhay** [shurans/sscnet#27]
Hi @shurans ,
I loved the paper and was trying the implementation on ubuntu 16.04. I am not able to install it properly.
If I follow what is given then I get errors because after adding "export PYTHONPATH=~/build_master_release/python:$PYTHONPATH", it changes the location of python and caffe does not work, which is basically installed in **caffe_code/caffe3d_suncg** as mentioned in the instructions.
If I do not update PYTHONPATH variable then I get following error: 

**[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 7:20: Message type "caffe.LayerParameter" has no field named "suncg_data_param".
F1114 03:29:31.448052 15134 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: demo.txt
*** Check failure stack trace: ***
Aborted (core dumped)**

If someone could suggest me something, it would be really helpful. I am stuck at this for quite a long. I have already tried issues #15 and #7 . Both things didn't work out for me.
Thanks in advance.

**Comment by KnightOfTheMoonlight** [comment]
Can you explain the way you compile sscnet? I checked your answer to [15](https://github.com/shurans/sscnet/issues/15) It seems like you compile it with cmake.

**Comment by Pratapabhay** [comment]
Hi @KnightOfTheMoonlight ,
Firstly I tried to compile it in the same manner as mentioned. These are the steps:

Modify the Makefile.config file based on my system. 
 cd caffe_code/caffe3d_suncg
      Installed Caffe here using this link : https://yangcha.github.io/Caffe-Conda/
make -j40 && make pycaffe

Export path
export LD_LIBRARY_PATH=~/build_master_release/lib:/usr/local/cudnn/v5/lib64:~/anaconda2/lib:$LD_LIBRARY_PATH
export PYTHONPATH=~/build_master_release/python:$PYTHONPATH

The problem is that it is appending pythonpath with this **~/build_master_release/python**, and this path doesn't work properly. It can't import caffe properly, obviously because caffe is installed in here **cd caffe_code/caffe3d_suncg/caffe/** . 
If I remove **~/build_master_release/python** from PYTHONPATH then caffe is imported properly but then I get another error as mentioned in above comment.

When all this didn't work I compiled using cmake, with cmake "build_master_release" directory is not made, which is obvious since cmake creates its own Makefile. But in this procedure also while running the demo I get the same error as mention in previous comment.

Thanks for the help.

**Comment by KnightOfTheMoonlight** [comment]
At present, I think you might make some mistakes in the build process.
environment for me is:
Ubuntu 16.04
cuda 8
cudnn 
I use make for this code. And what I do is:
check the Makefile.config for my environment, following sscnet's setting.
make -j8 & make pycaffe
Then I have export 
```
export LD_LIBRARY_PATH=~/Research/code/sscnet/caffe_code/caffe3d_suncg/build_master_release/lib:$LD_LIBRARY_PATH 
export PYTHONPATH=~/Research/code/sscnet/caffe_code/caffe3d_suncg/build_master_release/python:$PYTHONPATH 
make -j8 & make pycaffe
Then I have export 
export LD_LIBRARY_PATH=~/Research/code/sscnet/caffe_code/caffe3d_suncg/build_master_release/lib:$LD_LIBRARY_PATH 
export PYTHONPATH=~/Research/code/sscnet/caffe_code/caffe3d_suncg/build_master_release/python:$PYTHONPATH 

```
 And for your check, the lib and python folder looks in this way:
lib folder -> `libcaffe.a  libcaffe.so  libcaffe.so.1.0.0-rc3`
python folder -> 'caffe'

I'm not pretty sure about the python folder, But I can find the pycaffe interfaces in caffe3d_suncg/python:
and under the folder, I have `caffe  classify.py  CMakeLists.txt  detect.py  draw_net.py  requirements.txt`

**Comment by Pratapabhay** [comment]
Thanks for the reply. I'll follow it. Just for the reference what is your caffe path? I mean where is your caffe installed?

**Comment by KnightOfTheMoonlight** [comment]
[caffe3d_suncg](https://github.com/shurans/sscnet/tree/master/caffe_code/caffe3d_suncg) this the caffe code for sscnet. So the path is  `sscnet/caffe_code/caffe3d_suncg` The author just puts it in the repository. If I didn't misunderstand what you ask.

**Comment by Pratapabhay** [comment]
I mean where is your caffe installed, the main caffe library? Not sscnet_caffe code but the main caffe library. 
I meant **https://github.com/BVLC/caffe** this.

**Comment by KnightOfTheMoonlight** [comment]
I'm confused... Why would you ask this. I think when you use sscnet, you just need to compile the caffe3d_suncg code(which is the revised version of caffe-rc3).

**Comment by Pratapabhay** [comment]
I tried all the steps but it's till not working for me. It may be some configuration issues. Could you just please check if you are able to **import caffe** after the following commands:

make -j8 & make pycaffe

export LD_LIBRARY_PATH=~/Research/code/sscnet/caffe_code/caffe3d_suncg/build_master_release/lib:$LD_LIBRARY_PATH 
export PYTHONPATH=~/Research/code/sscnet/caffe_code/caffe3d_suncg/build_master_release/python:$PYTHONPATH 

After this are you able to import caffe?
Because **import caffe** is not working for me and is the same error which I get when I run **python demotest_model.py**.
I think it's still caffe error. 

Thanks in Advance

**Comment by ywcmaike** [comment]
Hi, gays! I compile as the README.md said.  but when I run the script " python demotest_model.py " core dump;
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0329 19:40:27.403504 15038 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0329 19:40:27.403527 15038 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0329 19:40:27.403528 15038 _caffe.cpp:142] Net('demo.prototxt', 1, weights='../models/suncg_ft_nyu.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 7:20: Message type "caffe.LayerParameter" has no field named "suncg_data_param".
F0329 19:40:27.404366 15038 upgrade_proto.cpp:90] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: demo.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
@KnightOfTheMoonlight @Pratapabhay

**Comment by ywcmaike** [comment]
@Pratapabhay have you solved the problem?

**Comment by ywcmaike** [comment]
Hi, gay! I have solved the problem as @KnightOfTheMoonlight said. 
1) modify the makefile.config  in the directory of ("sscnet/caffe_code/caffe3d_suncg/") as followed:
cp Makefile.config.sscnet_example Makefile.config
and modify : I use the primitive python so :
PYTHON_INCLUDE := /usr/include/python2.7 \
                  /usr/local/lib/python2.7/dist-packages/numpy/core/include 
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial
  LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial
2）modify the CMakeList.txt in the directory of ("sscnet/caffe_code/caffe3d_suncg/") ， just to solve the compile error .  as followed:
include_directories("/usr/local/cuda-8.0/include")
set(CUDA_USE_STATIC_CUDA_RUNTIME OFF)
list(APPEND CUDA_NVCC_FLAGS "-arch=sm_20;-std=c++11;-O2;-DVERBOSE")
SET(CUDA_PROPAGATE_HOST_FLAGS OFF)
3）and Modify the Makefile also in the directory of ("sscnet/caffe_code/caffe3d_suncg/")
LIBRARIES += glog gflags protobuf boost_system boost_filesystem m hdf5_serial_hl hdf5_serial 
 NVCCFLAGS += -D_FORCE_INLINES -ccbin=$(CXX) -Xcompiler -fPIC $(COMMON_FLAGS) -std=c++11  
4)  in the directory of ("sscnet/caffe_code/caffe3d_suncg/")  run the compile 
 make -j8 & make pycaffe
5) export the environment path:
export LD_LIBRARY_PATH=~/build_master_release/lib:$LD_LIBRARY_PATH
export PYTHONPATH=~/build_master_release/python:$PYTHONPATH
6) run the modeltest.py
cd demo
python demotest_model.py

end!
I hope you help somebody!

**Comment by jiunyen-ching** [comment]
@ywcmaike May I know what version of Ubuntu, CUDA, and cuDNN did you use?
