### ISSUE TITLE
Parameters of suncg_data_layer

### ISSUE THREAD

**Issue by ph81323** [shurans/sscnet#3]
Hi, 
I've read your paper and tried to understand parameters in sscnet. There still are some questions.
In data layer,
what does "seg_class_weight" mean? I thought that there are 11 classes in NYU dataset, why there are 17 weights in data layer?
And how about "occ_class_weight" parameter?
Could you please explains them? Thanks a lot!

**Comment by shurans** [comment]
seg_class_weight is weight for each semantic class. The weights beyond the number of classes will not be used. In our final model they are all set equally as 1. "occ_class_weight" is not used in our final model.

**Comment by ph81323** [comment]
Got it! Thanks for explaining.
