### ISSUE TITLE
Does synthetic data help?

### ISSUE THREAD

**Issue by mgarbade** [shurans/sscnet#31]
I'm just re-reading your paper. In the section "Does synthetic data help?" you stated that "especially for the semantic scene completion task having  [synthetic data] would give a 10.3% improvement in IoU."

Table 1:  
SSCNet (NYU)                   = 55.1 IoU [scene completion] and 24.7 ?avg? [semantic scene completion]
SSCNet (SUNCG)             = 53.2 IoU [scene completion] and 20.2 ?avg? [semantic scene completion]
SSCNet (SUNCG + NYU)  = 56.6 IoU [scene completion] and 30.5 ?avg? [semantic scene completion]

I can see the 10.3 % improvement comparing the avg (class wise IoU?) values 20.2 to 30.5.
However doesn't one rather have to compare the first and the third line? (24.7 vs 30.5)
I assume NYU means it is trained from scrath on the 795 train images from nyu_depth_v2, right?

**Comment by shurans** [comment]
@mgarbade Yes, you are right the comparison should be between 24.7 to 30.5 which is 5.8% improvement.
