### ISSUE TITLE
How to generate the style of the "error visualization" in Figure 15 or 16 ?

### ISSUE THREAD

**Issue by TracelessLe** [shurans/sscnet#38]
Thanks for your outstanding work about semantic scene completion from a single depth image. We get some prediction results and want to compare with the ground truth to show the difference. We find the style of the "error visualization" in Figure 15 or 16 is pretty for explanation. 
![360 17001025399057](https://user-images.githubusercontent.com/22371026/40414915-270b97aa-5eac-11e8-8da7-d68092714296.png)
Would you tell me how did you generate the style, in manual or use some visualization software?

**Comment by mgarbade** [comment]
A friend of mine compiled a small [blender script](https://stackoverflow.com/a/50424332/2191652) to generate voxel outputs.

**Comment by TracelessLe** [comment]
@mgarbade Thank you very much!
