### ISSUE TITLE
How to visualize the ply files which the evaluation process generates?

### ISSUE THREAD

**Issue by TracelessLe** [shurans/sscnet#5]
I use Matlab to observe the format of ply files, and find that it is different from the organized format. Then I try to use some 3D visualization software to deal with them but fail. Would you tell me how to solve the problem? Thanks a lot.

**Comment by shurans** [comment]
You can open the mesh use Meshlab (http://www.meshlab.net/)

**Comment by TracelessLe** [comment]
Thank you very much! I succeed.

**Comment by mgarbade** [comment]
@TracelessLe  @shurans  Does anyone know how to get the 3D rendering / lighting effect using meshlab?
See also this question [https://stackoverflow.com/q/48214144/2191652](here)

**Comment by LongruiDong** [comment]
> @TracelessLe @shurans Does anyone know how to get the 3D rendering / lighting effect using meshlab?
> See also this question [https://stackoverflow.com/q/48214144/2191652](here)

hello ,
I have watched the your excellent video tutorial from https://stackoverflow.com/questions/48214144/how-to-export-3d-pointcloud-as-a-rendered-voxel-grid
.
In the video, Blender need a mat file as the input, but I can not convert .ply files(output of SSCNet evaluation codes) to .mat file, can you share relevant codes ?
what's more,I also made an issue at https://github.com/cagcoach/BlenderPlot/issues/1#issue-387374041
Thank you~~!!
