### ISSUE TITLE
caffe的编译问题。在make test这一步。

### ISSUE THREAD

**Issue by CJohnny** [shurans/sscnet#6]
您好！
我正在编译caffe3d_suncg，进行到make test的时候报错“fatal error:caffe/layers/log_layers.hpp: no such file or directory”
在对BVLC的caffe进行到这一步的时候正常通过。
您的caffe3d_suncg与BVLC的caffe相比，有很大改动吗？
我在考虑是不是直接把缺少的文件复制过来，但是，担心与您的其他代码不匹配。

**Comment by CJohnny** [comment]
Hello！
I‘m working on caffe3d_suncg, when I come to the step 'make test', it reports “fatal error:caffe/layers/log_layers.hpp: no such file or directory”
However, I go through this when compiling the caffe from BVLC. No error reported.
Are there major differences between your caffe3d_suncg and BVLC/caffe?
I'm considering simply copy those missing files from BVLC/caffe, but, I'm worried they are not compatible.

**Comment by shurans** [comment]
The code in caffe3d_suncg are different from BVLC/caffe. There are additional layers.
However, if you can successfully compile it ("make -j8 && make pycaffe" ). You can skip the 'make test' step, and try to run it.

**Comment by CJohnny** [comment]
@shurans cool. Thank you!
