### ISSUE TITLE
Downloaded data issues

### ISSUE THREAD

**Issue by CJohnny** [shurans/sscnet#9]
Hi, I'm trying to do this in your Readme.md, 
'Training:
    ...
    1.Training from scratch cd caffe_code/train/trainsuncg ./train.sh  
    ...
'
error says that ' List file not exist : ../../../../data/depthbin/SUNCGtrain_1_500/camera_list_train.list'
I did download the 'data' file and I didn't see that directory.
Any idea? thank you!

**Comment by shurans** [comment]
Did you run "download_suncgTrain.sh" to download SUNCG data? Is the data located in  ../../../../data/depthbin/ ?

**Comment by CJohnny** [comment]
@shurans Got it, I skipped some 'optional' step. on it!
